quarkus.datasource.db-kind=oracle
quarkus.datasource.username=system
quarkus.datasource.password=quarkus
quarkus.datasource.jdbc.url=jdbc:oracle:thin:@localhost:1521/XE
quarkus.http.cors-enable=true
quarkus.http.cors.origins=http://localhost:5173

quarkus.hibernate-orm.database.generation=update
quarkus.http.cors=true