# Banco de Dados Oracle
quarkus.datasource.db-kind=oracle
quarkus.datasource.username=system
quarkus.datasource.password=quarkus
quarkus.datasource.jdbc.url=jdbc:oracle:thin:@localhost:1521/XE
quarkus.hibernate-orm.database.generation=update


quarkus.http.cors=true

# Define quem pode acessar (seu Front-end Vue)
quarkus.http.cors.origins=http://localhost:5173

# Métodos permitidos (importante para o 'preflight' que falhou)
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS

# Headers que o navegador pode enviar
quarkus.http.cors.headers=Content-Type,Authorization

# Tempo que o navegador pode "lembrar" dessa permissão (opcional)
quarkus.http.cors.access-control-max-age=24H